class Additems28 < ActiveRecord::Migration
  def change
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s0_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s0_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s0_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s1_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s1_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s1_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s2_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s2_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s2_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s3_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s3_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s3_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s0_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s0_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s0_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s1_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s1_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s1_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s2_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s2_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s2_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s3_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s3_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s3_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s0_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s0_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s0_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s1_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s1_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s1_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s2_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s2_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s2_mjpeg_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s3_h265_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s3_h264_bitrate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s3_mjpeg_bitrate, :string
  end
end
