class AddNewitems15 < ActiveRecord::Migration
  def change
    
    add_column :userinputs, :h265, :string
    add_column :userinputs, :h264, :string
    add_column :userinputs, :mjpeg, :string
    add_column :userinputs, :nvideomode, :string
    add_column :userinputs, :videoin_c0_mode0_effectivepixel, :string
    add_column :userinputs, :r176x144, :string
    add_column :userinputs, :r320x240, :string
    add_column :userinputs, :r640x480, :string
    add_column :userinputs, :r800x600, :string
    add_column :userinputs, :r1280x960, :string
    add_column :userinputs, :r1600x1200, :string
    add_column :userinputs, :r2048x1536, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_0, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_1, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_2, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_3, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_4, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_5, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_6, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_7, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_8, :string
    add_column :userinputs, :videoin_c0_mode0_maxframerate_9, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_0, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_1, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_2, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_3, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_4, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_5, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_6, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_7, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_8, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h265_9, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_0, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_1, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_2, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_3, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_4, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_5, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_6, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_7, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_8, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_h264_9, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_0, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_1, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_2, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_3, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_4, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_5, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_6, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_7, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_8, :string
    add_column :userinputs, :videoin_c0_mode0_maxfps_mjpeg_9, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_0, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_1, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_2, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_3, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_4, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_5, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_6, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_7, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_8, :string
    add_column :userinputs, :videoin_c0_mode1_maxframerate_9, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_0, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_1, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_2, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_3, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_4, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_5, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_6, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_7, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_8, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h265_9, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_0, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_1, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_2, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_3, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_4, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_5, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_6, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_7, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_8, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_h264_9, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_0, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_1, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_2, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_3, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_4, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_5, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_6, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_7, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_8, :string
    add_column :userinputs, :videoin_c0_mode1_maxfps_mjpeg_9, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_0, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_1, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_2, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_3, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_4, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_5, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_6, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_7, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_8, :string
    add_column :userinputs, :videoin_c0_mode2_maxframerate_9, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_0, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_1, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_2, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_3, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_4, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_5, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_6, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_7, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_8, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h265_9, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_0, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_1, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_2, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_3, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_4, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_5, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_6, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_7, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_8, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_h264_9, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_0, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_1, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_2, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_3, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_4, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_5, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_6, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_7, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_8, :string
    add_column :userinputs, :videoin_c0_mode2_maxfps_mjpeg_9, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s0_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s0_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s0_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s1_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s1_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s1_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s2_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s2_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s2_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s3_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s3_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode0_defaultsetting_s3_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s0_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s0_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s0_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s1_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s1_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s1_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s2_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s2_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s2_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s3_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s3_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode1_defaultsetting_s3_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s0_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s0_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s0_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s1_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s1_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s1_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s2_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s2_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s2_mjpeg_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s3_h265_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s3_h264_framerate, :string
    add_column :userinputs, :videoin_c0_mode2_defaultsetting_s3_mjpeg_framerate, :string
  end
end
